spring.application.name=LexCloud

# URL de la base de datos (reemplaza 'nombre_tu_bd' por el nombre real)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

# Credenciales
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Ruta donde se guardarán los documentos legales
lexcloud.upload.dir=uploads/documentos

# Validar que Java y Postgres coincidan sin modificar nada
spring.jpa.hibernate.ddl-auto=validate
# Ver qué consultas se hacen (útil en desarrollo)
spring.jpa.show-sql=true
# Asegurar que hable el lenguaje correcto de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
